const SET_DESC = 'SET_DESC';
const SET_PRICE_NEGOTIABLE = 'SET_PRICE_NEGOTIABLE';
const SET_PRICE = 'SET_PRICE';
const SET_CATEGORY = 'SET_CATEGORY';
const SET_TITLE = 'SET_TITLE';
const RESET_AD = 'RESET_AD';
const SET_CATEGORIES = 'SET_CATEGORIES';
export {
    SET_DESC,
    SET_PRICE_NEGOTIABLE,
    SET_PRICE,
    SET_CATEGORY,
    SET_TITLE,
    RESET_AD,
    SET_CATEGORIES
}