
const SET_NAME = 'SET_NAME';
const USER_LOGOUT = 'USER_LOGOUT';
const SET_EMAIL = 'SET_EMAIL';
const SET_PASSWORD = 'SET_PASSWORD';
const SET_REMEMBER_PASSWORD = 'SET_REMEMBER_PASSWORD';
const USER_REGISTER = 'USER_REGISTER';
const SET_STATELOCK = 'SET_STATELOCK';
const SET_CONFIRM_PASSWORD = 'SET_CONFIRM_PASSWORD';
export {
    SET_CONFIRM_PASSWORD,
    SET_EMAIL,
    SET_PASSWORD,
    SET_REMEMBER_PASSWORD,
    SET_NAME,
    USER_LOGOUT,
    USER_REGISTER,
    SET_STATELOCK
};